### ISSUE TITLE
Flag for simple std output

### ISSUE THREAD

**Issue by mr-const** [fastlane/gym#105]
Is it possible to add some flag for simple log output? We use Jenkins for builds and console log looks pretty ugly. And it seems that gym has some issues with buffering or something like that, because live jenkins log waits on first build output string and after build completion spits tons of output.
Here is an example (Timestamp to the left - generated by jenkins, to the right - from gym):

```
00:00:49.597 [37mINFO [2015-09-24 14:54:16.48]: [0m[33mset -o pipefail && xcodebuild -scheme 'MyProject' -project './MyProject.xcodeproj' -configuration 'Release' -destination 'generic/platform=iOS' -archivePath '/var/lib/jenkins/Library/Developer/Xcode/Archives/2015-09-24/MyProject-Release-2.1.1005 2015-09-24 14.54.16.xcarchive' PROVISIONING_PROFILE=77a8aad0-c3fd-46a6-808e-7468b39aa65a archive CODE_SIGN_IDENTITY='iPhone Distribution: MyProject Limited' | xcpretty[0m
00:00:49.597 [36m
00:00:49.597 -----[0m
00:05:57.542 [36m▸ Building MyProject/MyProject[Release]
[0m[36m▸ Precompiling MyProject/Source/MyProject-Prefix.pch
...
[0m[36m▸ Signing /var/lib/jenkins/Library/Developer/Xcode/DerivedData/MyProject-egvicvrwgqirqlhhtvkhpxtjsjuo/Build/Intermediates/ArchiveIntermediates/MyProject/InstallationBuildProductsLocation/Applications/MyProject.app
[0m[36m▸ Touching MyProject.app.dSYM                                                                                                                                                                                    
[0m[36m-----
00:08:22.704 [0m
00:08:22.704 [37mINFO [2015-09-24 15:01:49.00]: [0m[32mSuccessfully stored the archive. You can find it in the Xcode Organizer.[0m
```

**Comment by pkostenko** [comment]
Yes, I agree. It would be especially useful for CI systems to have the ability to disable xcpretty and write the raw output to the console.

**Comment by KrauseFx** [comment]
`gym` will automatically print out the raw output if there is a build error, enabling you to resolve the issue. If everything works without problems you don't have to read the complete build output, right? 

So the only use case is when you want to see the build output *while* the Jenkins job is running?

**Comment by pkostenko** [comment]
Yes, the first use case would be seeing the build output in real-time (this is particularly nicely implemented in TeamCity).
The second use case - seeing all warnings + build settings.
The third use case - analyzing the build logs in case technically a build has succeeded, but the application was not packaged correctly (some resources are missing, signing with wrong entitlements, etc.).

**Comment by KrauseFx** [comment]
@pkostenko as it is now you can access the raw `xcodebuild` output in `~/Library/Logs/gym`

**Comment by pkostenko** [comment]
@KrauseFx It implies that I need to have an access to the file system, which is not always possible in case of CI server. Meanwhile, the build output in WebUI as always available.

**Comment by xfreebird** [comment]
@pkostenko you could output the log file at the end of gym action.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1852. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
