### ISSUE TITLE
Runtime error archiving 

### ISSUE THREAD

**Issue by gametimebuildserver** [fastlane/gym#113]
```
The following build commands failed:
Libtool /Users/bserver/Library/Developer/Xcode/DerivedData/Gametime-afosxnghsgtxcyajgrkdraetxdxg/Build/Intermediates/ArchiveIntermediates/Beta/IntermediateBuildFilesPath/Pods.build/Beta-iphoneos/Braintree.build/Objects-normal/arm64/libBraintree.a normal arm64
(1 failure)
[17:52:18]: Exit status: 65
/Library/Ruby/Gems/2.0.0/gems/gym-0.8.4/lib/gym/error_handler.rb:52:in `handle_build_error': Error building the application - see the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.4/lib/gym/runner.rb:80:in `block in build_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.18.2/lib/fastlane_core/command_executor.rb:51:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.18.2/lib/fastlane_core/command_executor.rb:51:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.4/lib/gym/runner.rb:76:in `build_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.4/lib/gym/runner.rb:10:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.4/lib/gym/manager.rb:8:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.4/lib/gym/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.4/lib/gym/commands_generator.rb:58:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.4/lib/gym/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.4/bin/gym:6:in `<top (required)>'
	from /usr/local/bin/gym:23:in `load'
	from /usr/local/bin/gym:23:in `<main>'
```

command I was running: 

gym --workspace "projname.xcworkspace" --scheme "Beta" -o $HOME/Desktop/build/ --use_legacy_build_api --clean

**Comment by KrauseFx** [comment]
Does it work without specifying the `use_legacy_build_api` parameter? Do you get a build error when building using Xcode? Did you select the right version of Xcode?

**Comment by joshdholtz** [comment]
I am also seeing this same `Exit status: 65` stuff. I will let you know when I figure out what is actually causing it :wink:

**Comment by joshdholtz** [comment]
It's the worst error because it literally doesn't give any error information :grimacing:

**Comment by DoubleMalt** [comment]
I'm also seeing error 65 ... only in my case what fails is CodeSign:

```
The following build commands failed:
CodeSign /Users/doublemalt/Library/Developer/Xcode/DerivedData/treats.-dlojmxuiowzguhegzittvgdwvujm/Build/Intermediates/ArchiveIntermediates/treats./InstallationBuildProductsLocation/Applications/treats..app
(1 failure)
[18:10:03]: Exit status: 65
```

**Comment by joshdholtz** [comment]
@KrauseFx My error was actually due to a "run script" in the build phases that was failing silently :grimacing: You are still perfect in my eyes :wink:

**Comment by NSCabezon** [comment]
How did you know it was the run script?? I'm getting the same error:

```objc
Exit status: 65
/Library/Ruby/Gems/2.0.0/gems/gym-1.1.5/lib/gym/error_handler.rb:52:in `handle_build_error': Error building the application - see the log above (RuntimeError)
```

**Comment by joshdholtz** [comment]
@NSCabezon I actually went into Xcode and and sifted through all the output during the build phases. The output showed that one of my run scrips was failing but Xcode seemed to not care and still built anyway (unlike Gym or Shenzen which errored out).

**Comment by mfmendiola** [comment]
@joshdholtz Thank you!  The error returned by fastlane was mostly uninformative, but we found the culprit by looking at the output during the build phases.  Saved us a lot of time.

**Comment by joshdholtz** [comment]
@mfmendiola I believe this is an `xcodebuild` issue (hiding the output) but I'm glad that helped :blush:

**Comment by madnik** [comment]
As @KrauseFx suggest always make sure use correct xcode-select version. I had the issue for a project that successfully built in xcode 7. My Issue was xcode command line tools configured to use previous version, which was not aware of compiling swift 2 stuff. U can check this at XCode -> Preferences-> Locations-> Command line tools.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1849. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
