### ISSUE TITLE
Build command hangs on "Touching MyApp.app"

### ISSUE THREAD

**Issue by evansolomon** [fastlane/gym#130]
I am brand new to Fastlane, so I'm probably missing something obvious here. I am trying to setup a lane using gym and ran into what seems like a stuck command.

If I run something like this: `gym build --verbose --scheme MyApp --project './MyApp.xcodeproj'` I get a bunch of output for things getting built/linked/compiled/etc and finally it prints "Touching MyApp.app". The last message just stays there (seemingly) forever and nothing happens.

I tried running the underlying `xcodebuild` command directly and got a similar but different problem. I ran `xcodebuild -scheme 'MyApp' -project './MyApp.xcodeproj' -destination 'generic/platform=iOS' archive` and got a bunch of logging output until it got to a "CopySwiftLibs" step. Just like the "Touching MyApp.app" step nothing happens once this log is printed.

I tried searching for similar issues on both steps but couldn't find anything obviously related.

I'm wondering if (1) I'm doing something clearly wrong and (2) the touching app/copying swift libs logs are in any way related.

Thanks.

Edit: Fyi this is with gym version 1.1.1

**Comment by evansolomon** [comment]
Btw in case this is relevant, my app also has a share extension bundled with this. This has never really changed the way we've used Xcode's build tools, but figured it might be relevant here.

**Comment by luissilvaos** [comment]
Same issue here. Any update on this?

**Comment by jshultz** [comment]
i'm having the same problem. did anyone ever resolve this?

**Comment by dannob** [comment]
@jshultz  I just ran into this issue.  I found that my build post-action script was having problems.  It caused gym to hang.

**Comment by RichAppz** [comment]
Hey, did anyone get to the bottom of this issue? I have this issue at the moment and it is driving me a little crazy!!! Thanks in advance.

**Comment by mpirri** [comment]
Hiya, folks! Sorry for the delay in getting back to you about this.

Question - if you use gym to build a bone-stock new xcode project, do you see a similar behavior? (it the problem with gym alone, or something about your project causing this behavior)

Also - inspired by @dannob 's comment, do you have any post-build run script build phases that might be causing problems? My experiments indicate that these run script build phases would happen BEFORE the Touching step, but worth looking into.

**Comment by Pretz** [comment]
One data point: I ran in to this issue recently and found the same problem was happening when I ran `xcodebuild` on its own. Rebooting my computer made the problem go away. Thanks Xcode. 🙄

**Comment by jtbthethird** [comment]
A reboot helped me as well.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1847. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
