### ISSUE TITLE
Gymfile seemingly ignored

### ISSUE THREAD

**Issue by johncblandii** [fastlane/gym#156]
```
scheme "Example"

sdk "iphoneos9.0"

clean true

output_directory "./build"    # store the ipa in this folder
output_name "MyApp"           # the name of the ipa file
```

I took this exact one and expected some error for not finding the scheme, etc yet nothing happened. It was a sanity check on whether or not my actual `Gymfile` was the problem or not.

My conclusion: the `Gymfile` is completely ignored. Thoughts?

Note:
- Cordova project
- gym 1.1.6

**Comment by johncblandii** [comment]
I also tried this with `fastlane` and it still fails to properly use the values from the `Gymfile`.

I have to be doing something wrong. Any help would be appreciated.

**Comment by KrauseFx** [comment]
That's weird. Is your `Gymfile` in the same directory as your project? Can you share a screenshot of your setup in Finder

**Comment by johncblandii** [comment]
Sure thing. It's an Ionic project (Angular on top of Cordova).

BTW, the push has been AMAZING for me. I think this project will be my go-to for every mobile project I do. Simply put: thank you!

![project](https://www.dropbox.com/s/1sopelf39pxi3aj/Screenshot%202015-12-10%2022.37.02.png?dl=1)

**Comment by cybertk** [comment]
Same issue here

**Comment by cybertk** [comment]
Is this fixed by #170?

**Comment by KrauseFx** [comment]
Yeah, this should be fixed :+1:

**Comment by johncblandii** [comment]
Ok, will revisit soon to verify.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1837. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
