### ISSUE TITLE
Can't pass arbitrary build settings

### ISSUE THREAD

**Issue by hborders** [fastlane/gym#189]
Please add a parameter for arbitrary build settings.

The `xcodebuild` manpage lists the following parameter order:

```
xcodebuild -workspace name.xcworkspace -scheme schemename [[-destination destinationspecifier] ...] [-destination-timeout value] [-configuration configurationname] [-sdk [sdkfullpath | sdkname]] [action ...] [buildsetting=value ...] [-userdefault=value ...]
```

but when I invoke `gym` within my `Fastfile`:

```
gym(
      scheme: "Foo",
      output_directory: "build",
      xcargs: "BAR=baz"
    )
```

I get the following `xcodebuild` invocation:

```
xcodebuild -scheme 'Foo' -project './Foo.xcodeproj' -destination 'generic/platform=iOS' -archivePath '/Users/me/Library/Developer/Xcode/Archives/2016-01-13/Foo 2016-01-13 10.33.25.xcarchive' BAR=baz archive
```

which results in the following error:

```
sh: line 1: archive: command not found
[10:33:30]: Exit status: 127

[!] Error building the application - see the log above
```

If I move `archive` before `BAR=baz` and manually invoke `xcodebuild`, everything works:

```
xcodebuild -scheme 'Foo' -project './Foo.xcodeproj' -destination 'generic/platform=iOS' -archivePath '/Users/me/Library/Developer/Xcode/Archives/2016-01-13/Foo 2016-01-13 10.33.25.xcarchive' archive BAR=baz
```

**Comment by mgrebenets** [comment]
It must be also related to use of `-archivePath` and `archive`.
I'm pretty sure I had issues before with `xctool` when I put `-archivePath <path>` _before `archive`. In my case the error was like "-archivePath invalid action".

Same might be true here and the order of `archive` and `-archivePath` makes it fail.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1827. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
