### ISSUE TITLE
Improve gym error handling for export archive

### ISSUE THREAD

**Issue by lacostej** [fastlane/gym#192]
When using ```gym```to export archives, xcodebuild error handling can sometimes be confusing.

By default, all output, standard and error, from the xcodebuild command, is outputted to the standard error (and not colorized). Then gym detects issues and appends an error message. Also, if a particular error happens, e.g. the xcodebuild standard log is now [concatenated](https://github.com/fastlane/gym/blob/master/lib/gym/error_handler.rb#L87-L88), also as an error (*in RED*).

* [In some cases, this helps](https://github.com/fastlane/gym/issues/168):
[gym 1.2.0 output](https://github.com/fastlane/gym/files/97327/xcode_no_devices.txt)
[xcode logs](https://github.com/fastlane/gym/files/97326/xcode_no_devices.zip)

* in others, the concatenated ERROR output doesn't add more information, and can confuse the user, as the real error is printed *in BLACK* (before "**EXPORT FAILED**"):
[gym 1.4.0 output](https://github.com/fastlane/gym/files/97324/xcode_no_err.txt)
[xcode logs](https://github.com/fastlane/gym/files/97325/xcode_no_err.zip)

Some ideas:
* be a bit smarter at deciding when to concatenate extra output
* colorize the xcodebuild output differently (for standard and error outputs?)

**Comment by KrauseFx** [comment]
Sounds great :+1:

**Comment by lacostej** [comment]
I looked into coloring the executed output command differently and here are my findings:

* PTY.spawn merges stdout and stderr
* if we move away from PTY.spawn, e.g. to popen3, we need to be careful at not creating deadlocks (either using threads or using select). Also we might lose some colors (e.g. by default rspec doesn't force coloring on its output for non tty environments).

**Comment by lacostej** [comment]
Just to take note of this: I push the work on pluggable Runners (to exclude PTYs) before that one). See fastlane/fastlane_core#73

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1826. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
