### ISSUE TITLE
"No 'teamID' specified and no team ID found in the archive"

### ISSUE THREAD

**Issue by AvdLee** [fastlane/gym#204]
Using gym as followed from the terminal:
```
gym build -s MyApp
```

I'm getting the following error:
```
Error Domain=IDEFoundationErrorDomain Code=1 "No 'teamID' specified and no team ID found in the archive" UserInfo={NSLocalizedDescription=No 'teamID' specified and no team ID found in the archive}
```

Any idea how to fix this?

I've checked my team setting in the project, which is setted correctly.

**Comment by leecrossley** [comment]
I'm also experiencing this issue with export_method "ad-hoc" in my gymfile

**Comment by Sali0m** [comment]
Having the same issue over here

`gym --export_method enterprise use_legacy_build_api --scheme OurScheme`

Resulting in this:

```
2016-02-15 15:14:07.809 xcodebuild[98931:1626590] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/jc/70y7nvgs2ml9yvlh6v5l2hv80000gn/T/6Play_2016-02-15_15-14-07.809.xcdistributionlogs'.
2016-02-15 15:14:08.156 xcodebuild[98931:1626590] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7f9c2b5d2e00>: Error Domain=IDEFoundationErrorDomain Code=1 "No 'teamID' specified and no team ID found in the archive" UserInfo=0x7f9c2b65ad10 {NSLocalizedDescription=No 'teamID' specified and no team ID found in the archive}
error: exportArchive: No 'teamID' specified and no team ID found in the archive

Error Domain=IDEFoundationErrorDomain Code=1 "No 'teamID' specified and no team ID found in the archive" UserInfo=0x7f9c2b65ad10 {NSLocalizedDescription=No 'teamID' specified and no team ID found in the archive}
```

I've checked that the server has the certificate and trusts them, and also checked for the provisioning profiles which are all on the server. 
Any Idea at what to try next?

**Comment by aimak** [comment]
We ( @Sali0m, @delannoyk and I) found our error : it turns out that `use_legacy_build_api` should actually be `--use_legacy_build_api` :

`gym --export_method enterprise --use_legacy_build_api --scheme OurScheme`

When did _that_ change ?

**Comment by EricKuck** [comment]
I'm getting this error as well now on projects that built fine before. I haven't updated Xcode, only fastlane/gym. I'm NOT specifying an export_team_id, but I never was. Not sure why it would be required now when it always worked before.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1825. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
