### ISSUE TITLE
After failed .ipa upload, fastlane selects prior build and submits for review

### ISSUE THREAD

**Issue by owurman** [fastlane/gym#210]
I used fastlane to update my app to version 3.1.3. The CFBundleVersion was 3.1.3.1. I had to self-reject this one because of a bug which I fixed, then I tried to upload another .ipa with CFBundleVersion 3.1.3.2 with fastlane, which failed.

Rather than detect the failure and stop, fastlane proceeded to select 3.1.3.1 and submit it for review again.

**Comment by vpolouchkine** [comment]
Can you share your fastlane setup (version and Fastfile)?

**Comment by owurman** [comment]
1.59.0

Redacted comments, unused lanes and project name (I'm paranoid, don't really know why). The relative paths might throw you off: I have multiple targets and run fastlane out of their various subdirectories. All of their Fastfiles and Deliverfiles are symbolic links to the main ones, with just some different ENV variables. The failure was caused by the WWDR certificate issue (documented by https://github.com/fastlane/gym/issues/100). I think I had fallen back on use_legacy_build_api and that was causing other signing issues, but now I can't remember. It's been removed from the Fastfile since but I've noted where it was.


`fastlane_version "1.59.0"

default_platform :ios

platform :ios do


  def build_ipa
    gym(
      workspace: "../../{project}.xcodeproj/project.xcworkspace",
      scheme: ENV["SCHEME"],
      configuration: "Distribution"
      #may have had use_legacy_build_api: true here when initially produced
    )
  end

  lane :update do
    ENV["DELIVER_FORCE_OVERWRITE"] = "1"
    Dir.chdir('..') {
      system('deliver download_metadata')
    }
    if !system("grep -e \"^#{ENV["APP_NAME"]}$\" metadata/en-US/name.txt")
      abort("name.txt doesn't match Config")
    end
    system('./increment_build.sh')
    sigh
    build_ipa()
    #deliver(force: true, skip_screenshots: true)
    deliver(force: true, skip_screenshots: true, submit_for_review: true)
  end
  
end
`

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1824. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
