### ISSUE TITLE
Error resolving conflict between options: 'workspace' and 'project'

### ISSUE THREAD

**Issue by dpettit** [fastlane/gym#212]
On "Step: gym" I receive the following error:

```
///////////////////////////////////////////
[08:09:32]: -------------------------------------------------
[08:09:32]: --- Step: Verifying required fastlane version ---
[08:09:32]: -------------------------------------------------
[08:09:32]: fastlane version valid
[08:09:32]: ------------------------------
[08:09:32]: --- Step: default_platform ---
[08:09:32]: ------------------------------
[08:09:32]: Driving the lane 'ios appstore' 🚀
[08:09:32]: -----------------
[08:09:32]: --- Step: gym ---
[08:09:32]: -----------------
[08:09:32]: Using legacy build system - waiting for radar to be fixed: https://openradar.appspot.com/radar?id=4952000420642816
[08:09:32]: Error resolving conflict between options: 'workspace' and 'project'
[08:09:32]: Variable Dump:
[08:09:32]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios appstore"}
[08:09:32]: You can only pass either a 'workspace' or a 'project', not both

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gym                                 | 0           |
+------+-------------------------------------+-------------+

[08:09:32]: fastlane finished with errors

[!] You can only pass either a 'workspace' or a 'project', not both
///////////////////////////////////
```

In my fastlane config files, the only place I can see that I'm passing either of these is in the SNAPFILE, where I'm passing the project, not the workspace.  Any ideas on what is going on or how to fix?  It just started showing up a couple of days ago after my latest fastlane update.

**Comment by KrauseFx** [comment]
Can you share your `Fastfile` and a screenshot of your project directory

**Comment by dpettit** [comment]
Here's my Fastfile:

![screen shot 2016-02-15 at 8 35 01 am](https://cloud.githubusercontent.com/assets/403463/13052945/151bd016-d3bf-11e5-9bce-46baf7a5b9f3.png)

And here's my project directory:

![screen shot 2016-02-15 at 8 36 12 am](https://cloud.githubusercontent.com/assets/403463/13052981/40cee1bc-d3bf-11e5-9455-d40b78b421bb.png)

**Comment by olegoid** [comment]
Thanks for provided information @dpettit, could you also share the contents of your `Gemfile`?

**Comment by KrauseFx** [comment]
Ohhh, I missed that there is a `Gymfile` outside the `fastlane` folder

**Comment by armadsen** [comment]
I'm seeing this same thing after updating to the latest version of fastlane today. I'm not specifying a workspace or project either, nor does my project folder contain a .xcworkspace file (other than the one internal to my .xcodeproj folder, of course).

As this has broken builds using fastlane, it'd be nice to know how to workaround it even before the underlying problem is fixed in a fastlane update.

**Comment by dpettit** [comment]
My Gymfile:
########################
scheme "tsbook"

use_legacy_build_api true
sdk "iphoneos9.2"

clean true

# store the .ipa in this folder
output_directory "/Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/Output-TS-ipa"

# The name of the .ipa file
output_name "TheAdventuresofLittleMunch-FirstDay-1.20"
########################

**Comment by KrauseFx** [comment]
This was fixed with https://github.com/fastlane/fastlane_core/pull/103, we're just about to push a new release. Please update using `sudo gem update fastlane_core` and let us know if that fixes this issue (Thanks @olegoid)

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1822. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
