### ISSUE TITLE
Feature Request: add Xcode version to build output

### ISSUE THREAD

**Issue by cbowns** [fastlane/gym#223]
Most of us have multiple versions of Xcode installed simultaneously, with all the betas which are always being sent out.

I'd love to have `gym` to print out some info about the toolchain it's using at the start of a build:

- `xcode-select -p`
- `CFBundleShortVersionString` and `CFBundleIconFile` for the Xcode used by `xcode-select`

Background info:

It's pretty hard to distinguish an Xcode beta from a regular Xcode. Almost nothing in its Info.plist indicates it's a beta… except its `CFBundleIconFile` value. (Seems like a good Radar to file, now that I think about it. bc this seems brittle.) (`Xcode.app` here is Xcode 7.3 beta 3, btw.)

```
# defaults read /Applications/Xcode-7.2.app/Contents/Info.plist CFBundleShortVersionString
7.2.1
# defaults read /Applications/Xcode-7.2.app/Contents/Info.plist CFBundleIconFile
Xcode

# defaults read /Applications/Xcode.app/Contents/Info.plist CFBundleShortVersionString
7.3
# defaults read /Applications/Xcode.app/Contents/Info.plist CFBundleIconFile
XcodeBeta
```

**Comment by KrauseFx** [comment]
I like the idea. As far as I know `gym` already prints out the path to the Xcode it uses, right?

**Comment by KrauseFx** [comment]
I like the idea. As far as I know `gym` already prints out the path to the Xcode it uses, right?

**Comment by cbowns** [comment]
Nope, it invokes it with `xcrun` so there's never a path printed out with what Xcode is being used.

**Comment by lacostej** [comment]
Note: we already have `FastlaneCore::Helper.xcode_version` and `FastlaneCore::Helper.xcode_path`, which could be added to the printed config output and used to fetch more information.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1819. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
