### ISSUE TITLE
xcpretty missing after fresh fastlane install

### ISSUE THREAD

**Issue by hborders** [fastlane/gym#235]
I installed fastlane with `sudo gem install fastlane --verbose` on OSX 10.11.3. I had to reinstall after I upgraded from OSX 10.10.5. When I ran `fastlane`, I saw the following output on my `gym` step:

```
[10:24:25]: -----------------
[10:24:25]: --- Step: gym ---
[10:24:25]: -----------------
[10:24:25]: xcrun xcodebuild -list -project './Foo.xcodeproj'

+----------------------+----------------------+
|            Summary for gym 1.6.1            |
+----------------------+----------------------+
| scheme               | Foo                |
| export_method        | ad-hoc               |
| output_directory     | ./build              |
| project              | ./Foo.xcodeproj   |
| destination          | generic/platform=iOS |
| output_name          | Foo                |
| clean                | false                |
| silent               | false                |
| use_legacy_build_api | false                |
| buildlog_path        | ~/Library/Logs/gym   |
+----------------------+----------------------+

[10:24:29]: $ set -o pipefail && xcodebuild -scheme 'Foo' -project './Foo.xcodeproj' -destination 'generic/platform=iOS' -archivePath '/Users/bordersh/Library/Developer/Xcode/Archives/2016-03-07/Foo 2016-03-07 10.24.29.xcarchive' archive | tee /Users/bordersh/Library/Logs/gym/Foo-Foo.log | xcpretty
[10:24:29]: ▸ sh: xcpretty: command not found
^C
Cancelled... use --verbose to show the stack trace
```

I waited a minute or two and then killed the process because I didn't see any output.

Then, I ran `sudo gem install xcpretty --verbose` and everything seemed to work fine again. I guess there's a dependency missing somewhere?

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1813. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
