### ISSUE TITLE
Add Symbols folder to the ipa

### ISSUE THREAD

**Issue by CraigSiemens** [fastlane/gym#51]
It would be great if there was an option to add the `Symbols` folder to the `ipa` just like Xcode does so crash reports from iTunes Connect can be symbolicated.

I have been using a `fastlane` action to do this but I think it would be good if it was part of `gym`. I only know enough Ruby to make me dangerous, but here is the action if anyone want to add it to `gym`.

```ruby
ipa_path = File.expand_path(Actions.lane_context[Actions::SharedValues::IPA_OUTPUT_PATH])
app_name = File.basename(ipa_path, ".ipa")
folder_path = File.dirname(ipa_path)

Dir.mktmpdir do |dir|
    app_binary = File.join(dir, "Payload", "#{app_name}.app", app_name)
    symbols = File.join(dir, "Symbols")

    Actions.sh "unzip \"#{ipa_path}\" -d \"#{dir}\""
    Actions.sh "mkdir \"#{symbols}\""
    Actions.sh "xcrun symbols -noTextInSOD -noDaemon -arch all -symbolsPackageDir \"#{symbols}\" \"#{app_binary}\""

    all_folders = Dir.glob(File.join(dir, "*")).map { |f| "\"#{File.basename(f)}\"" }.join(" ")

    Actions.sh "cd \"#{dir}\" && zip -r \"#{ipa_path}\" #{all_folders}"
end
```

**Comment by KrauseFx** [comment]
Thanks for the code, is that something you wrote? This will be possible once I found a way to finish https://github.com/fastlane/gym/pull/47, as it uses the built-in Xcode feature.

**Comment by CraigSiemens** [comment]
Yup, I wrote the `fastlane` action. I found out about the `symbols` command from [here](http://faq.sealedabstract.com/xcodeCI/#create-symbol-files-with-this-one-weird-trick).

**Comment by KrauseFx** [comment]
Thanks for sharing, I'll take a closer look over the next few days :+1:

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/gym/releases/tag/0.6.0, this is now built-in into `xcodebuild`, could you give it a try?

**Comment by sylvainlaurent** [comment]
using fastlane 1.49.0, when gym starts it says include_symbols is enabled, but then when deliver uploads the IPA to ITC, it seems that there's no symbol (in ITC website, the uploaded build has "No" for "Includes Symbols").

**Comment by sylvainlaurent** [comment]
sorry, I was mistaken : after a couple of minutes of "processing" by ITC, the symbols are now available.
So far so good, I think this issue can be closed...

**Comment by akki7017** [comment]
It's been more than 12 hours since the build has finished processing, and still i can not see the symbols in iTC. using just default lane "fastlane beta"

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1869. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
