### ISSUE TITLE
Specify Gymfile

### ISSUE THREAD

**Issue by Reedyuk** [fastlane/gym#68]
At the moment, i want to have multiple gym files so that i have a different configuration for dev, ad-hoc and release.
Could you make it so that when i do gym i can specify a gymfile name e.g. 
"gym devGymFile"
"gym adHocGymFile"

Thanks

**Comment by KrauseFx** [comment]
I could add its own option for the `Gymfile`:
e.g.
```
gym --file "devGymfile"
```

What do you think?

**Comment by Reedyuk** [comment]
Yeah that's perfect.

**Comment by KrauseFx** [comment]
This is something I want to implement over the next few weeks. In the mean-time you can either store the `Gymfile` in different directories or pass values using environment variables.

**Comment by gbasile** [comment]
I have the a similar problem here. I have different parameters for different environment. It is possible to pass environment variables?

**Comment by KrauseFx** [comment]
@gbasile Sure, check out `gym --help` for all environment variables. Also, I recommend you use [fastlane](https://fastlane.tools) to support different environments.

**Comment by apouche** [comment]
Just tried `gym` for the first time really like that tool great job. 

Regarding this specific enhancement, most of the time the configuration we should target depends on the branch the code is on (for ex `master:  Release`, `other-branch: AdHoc...`, `some-dev-branch: Debug`.) So a better improvement (I think) would be to simple have on `Gymfile` but being able to make the switch between configurations based on the branch where the code lives in. 

So a switch based on a branch would probably be a better solution ? What do you think @KrauseFx ? Or simply an `ENV` switch ?

**Comment by KrauseFx** [comment]
@apouche You should should be able to do all that using `fastlane` :+1:

**Comment by apouche** [comment]
Indeed, that was the second step, I just add issues with the way the `increment_build_number` works, but I'll open a PR for few. Great job on fastlane, I disabled my build/upload scripts yesterday.

**Comment by puttin** [comment]
Any news on the `gym --file "devGymfile"`?

**Comment by KrauseFx** [comment]
@puttin Sorry, no plans yet

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1867. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
