### ISSUE TITLE
iOS 9 Invalid Swift Support

### ISSUE THREAD

**Issue by djtarazona** [fastlane/gym#81]
Has anyone been able to successfully submit a build to iTC / TestFlight for iOS 9 with `gym`?  I'm using Xcode 7 GM (along with El Capitan GM) and every time I submit my binary, I get an email with the following:

> Invalid Swift Support - The files libswiftsimd.dylib, libswiftCoreMedia.dylib, libswiftAVFoundation.dylib, libswiftGLKit.dylib don’t match /Payload/App.app/Frameworks/libswiftsimd.dylib, /Payload/App.app/Frameworks/libswiftCoreMedia.dylib, /Payload/App.app/Frameworks/libswiftAVFoundation.dylib, /Payload/App.app/Frameworks/libswiftGLKit.dylib. Make sure the files are correct, rebuild your app, and resubmit it. Don’t apply post-processing to /Payload/App.app/Frameworks/libswiftsimd.dylib, /Payload/App.app/Frameworks/libswiftCoreMedia.dylib, /Payload/App.app/Frameworks/libswiftAVFoundation.dylib, /Payload/App.app/Frameworks/libswiftGLKit.dylib.
>
> Once these issues have been corrected, you can then redeliver the corrected binary.

It seems like a lot of other people are having the same issue, so this probably isn't an issue with `gym`.  But I'm hoping some workaround can be added to `gym` in the meantime.

These links may help:

http://stackoverflow.com/questions/32526526/invalid-swift-support-files-don-t-match
http://stackoverflow.com/questions/26163856/invalid-swift-support-invalid-implementation-of-swift
https://forums.developer.apple.com/thread/17063

I'm going to try archiving with just Xcode and see if that works.

**Comment by djtarazona** [comment]
No luck with archiving and uploading directly from Xcode. :(

**Comment by Killectro** [comment]
@djtarazona I'm not on ElCap but I was able to use the latest version of `gym` to submit a working TestFlight build with the Xcode 7 GM installed (but it was almost double the size it normally is). This potentially could be related to #79 and [this issue](https://github.com/KrauseFx/fastlane/issues/519) but I would leave it up to @KrauseFx to clarify that.

**Comment by KrauseFx** [comment]
Could you update to `gym 0.5.0` https://github.com/fastlane/gym/releases/tag/0.5.0 and let me know if that resolves this issue? 

I'm also working on a new version of `gym` to use the Xcode 7 API for code signing.

**Comment by djtarazona** [comment]
I updated to `gym 0.5.0` but no luck. :(

I also tried archiving and uploading directly from Xcode and got the same error.  This is using Xcode 7 build 7A220 now (released today).

**Comment by KrauseFx** [comment]
Please subscribe to [this pull request](https://github.com/fastlane/gym/pull/83) to be notified once I'm finished implementing the new Xcode 7 API.

**Comment by ldiqual** [comment]
@djtarazona See https://github.com/CocoaPods/CocoaPods/issues/4188#issue-106748634 for two possible workarounds

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/gym/releases/tag/0.6.0, please update using `sudo gem update gym` and let me know if that works for you :rocket:

**Comment by KrauseFx** [comment]
Also, make sure to set the path to the new Xcode 7 using `xcode-select`

**Comment by djtarazona** [comment]
@KrauseFx No luck still. Exactly same error / email from Apple. :(

**Comment by KrauseFx** [comment]
@djtarazona and when you build and export using Xcode you don't get this error message?

**Comment by djtarazona** [comment]
@KrauseFx No I still get the error message when building and exporting (or rather uploading via Organizer's `Upload to App Store...` button).

This [appears to be an issue with Cocoapods](https://github.com/CocoaPods/CocoaPods/issues/4188), therefore I'm not sure if its appropriate for `gym` to address?  I've [opened a PR](https://github.com/CocoaPods/CocoaPods/pull/4221) that fixes the issue for me with Cocoapods but I'm not sure if its a one-fits-all solution for everyone.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1860. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
