### ISSUE TITLE
The following build commands failed: PhaseScriptExecution Run\ Script status: 65

### ISSUE THREAD

**Issue by mdeandreis** [fastlane/gym#87]
I´m running fastlane beta to upload a new version to iTunes Connect and Crashlytics using Jenkins
Here is the console output.

```
[36m▸ Building PepTest/PepTest [Release]
[0m[36m▸ Compiling AppDelegate.m                   
[0m[36m▸ Compiling DataViewController.m
[0m[36m▸ Compiling ModelController.m   
[0m[36m▸ Compiling PepTest_vers.c
[0m[36m▸ Compiling DataViewController.m
[0m[36m▸ Compiling AppDelegate.m       
[0m[36m▸ Compiling ModelController.m
[0m[36m▸ Compiling main.m           
[0m[36m▸ Compiling RootViewController.m
[0m[36m▸ Compiling PepTest_vers.c  
[0m[36m▸ Compiling main.m            
[0m[36m▸ Compiling RootViewController.m
[0m[36m▸ Linking PepTest           
[0m[36m▸ Linking PepTest
[0m[36m▸ Compiling LaunchScreen.xib
[0m[36m▸ Processing Info.plist     
[0m[36m▸ Generating 'PepTest.app.dSYM'
[0m[36m▸ Running script 'Run Script'      
[0m[36m** ARCHIVE FAILED **         
[0m[36m                    
[0m[36m
[0m[36mThe following build commands failed:
[0m[36mPhaseScriptExecution Run\ Script /Users/jenkins_pep/Library/Developer/Xcode/DerivedData/PepTest-esyyuloooxtppqguxflsuzrmmxon/Build/Intermediates/ArchiveIntermediates/PepTest/IntermediateBuildFilesPath/PepTest.build/Release-iphoneos/PepTest.build/Script-30F795351B94AC13006D7256.sh
(1 failure)
[37m[15:11:36]: [0mExit status: 65 
```

Thanks, 
Martin

**Comment by KrauseFx** [comment]
Does it work when running `gym` without Jenkins? How did you install and run Jenkins? Using homebrew?

**Comment by mdeandreis** [comment]
Yes, if I navigate to fastlane folder and run:
fastlane beta increment_build_number:true increment_version_number:false upload_to_testflight:true upload_to_crashlytics:true scheme:"PepTest" description:"Description", everything works fine.

Here is my fastlane file:
platform :ios do

  before_all do 
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    # cocoapods
    #gym # Build your app - more options available
    # xctool # run the tests of your app
  end

  private_lane :build_app do |options|
    if options[:increment_build_number]
      increment_build_number
    end

    if options[:increment_version_number]
      increment_version_number
    end

    scheme = options[:scheme]

    gym(scheme: scheme) # Build your app - more options available

  end

  desc "Runs all the tests"
  lane :test do
    #snapshot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    #snapshot
    build_app(options)
    sigh
  
    if options[:upload_to_testflight]
     #puts ENV['DELIVER_BETA_DESCRIPTION'] = options [:description]
     deliver(beta: true)
    end
   
   if options[:upload_to_crashlytics]
       crashlytics({
         crashlytics_path:'./Crashlytics.framework',
         api_token: 'XXXXXdXXX',
         build_secret: 'XXX8da6f19fXXXX',
         ipa_path: 'PepTest.ipa'
      })
   end
   
  end
end

**Comment by mdeandreis** [comment]
I run java -jar jenkins-cli.jar -s http://localhost:8080 build ios_build_and_upload -p increment_build_number=true -p increment_version_number=false -p upload_to_testflight=false -p upload_to_crashlytics=false -p scheme="PepTest" -p description="Description" on my Mac with my user and Jenkins is configured in another user called jenkins_pep. The jenkin´s job is ios_build_and_upload

**Comment by KrauseFx** [comment]
In your command you never run `fastlane`. Or is this only how you start Jenkins?

**Comment by mdeandreis** [comment]
In my job,  I run fastlane throw shell command. Here is my code:

#!/bin/bash -l

export PATH=/usr/local/bin:$PATH
cd $WORKSPACE
fastlane beta increment_build_number:$increment_build_number increment_version_number:$increment_version_number upload_to_testflight:$upload_to_testflight upload_to_crashlytics:$upload_to_crashlytics scheme:$scheme description:$description

if [ "$increment_build_number" = true ] || [ "$increment_version_number" = true ]; then
	git add .
	git commit -m "Changed version number-BUILD-$BUILD_ID"
fi

**Comment by mdeandreis** [comment]
I was working in this issue and I found that Crashlytics/Fabric is the problem. I have a script on build phases to run Fabric. If I remove the script everything works fine. I have installed the latest version of Fabric. Do you have any idea?

**Comment by beardouglas** [comment]
I have a feeling the Crashlytics framework isn't being properly linked or is in a different location. Were you already able to onboard apps to Fabric, or is this the first time you're trying?

**Comment by mdeandreis** [comment]
Today I updated gym and fastlane and everything works fine
Thanks!

I have a feeling the Crashlytics framework isn't being properly linked or
is in a different location. Were you already able to onboard apps to
Fabric, or is this the first time you're trying?

—
Reply to this email directly or view it on GitHub
<https://github.com/fastlane/gym/issues/87#issuecomment-142424952>.

**Comment by lacostej** [comment]
@mdeandreis is the issue fixed ? Can it be closed ?

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1857. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
