### ISSUE TITLE
Gym and xcodebuild -showBuildSettings

### ISSUE THREAD

**Issue by xfreebird** [fastlane/gym#94]
By default gym is calling ```xcrun xcodebuild -showBuildSettings -scheme 'DemoApp' -project './DemoApp.xcodeproj'``` to get all environment variables.

But those will not reflect the correct values, because the actual executed command will be:

```
xcodebuild -scheme 'DemoApp' -project './DemoApp.xcodeproj' -configuration 'Release' -destination 'generic/platform=iOS' -archivePath '/Users/nghimbovschi/Library/Developer/Xcode/Archives/2015-09-21/DemoApp 2015-09-21 15.58.54.xcarchive'  archive
```

This will change the some variables in the simple use cases, and a lot in cases when user is using additional xcodebuild arguments. For example ```-derivedDataPath mylocation```. In this case all ENV variables will point to different locations than the ones obtained initially.

In cases when one developer would want to use ```BUILD_DIR``` variable, it will point to the wrong location.

**Comment by lacostej** [comment]
I've tried implementing this as:

````
diff --git a/lib/gym/project.rb b/lib/gym/project.rb
index f98975e..6ba7200 100644
--- a/lib/gym/project.rb
+++ b/lib/gym/project.rb
@@ -89,7 +89,7 @@ module Gym
     def build_settings(key: nil, optional: true)
       unless @build_settings
         # We also need to pass the workspace and scheme to this command
-        command = "xcrun xcodebuild -showBuildSettings #{BuildCommandGenerator.project_path_array.join(' ')}"
+        command = "xcrun xcodebuild -showBuildSettings #{BuildCommandGenerator.options.join(' ')}"
         Helper.log.info command.yellow unless Gym.config[:silent]
         @build_settings = `#{command}`
       end
`````

But this breaks some tests:

````
  1) Gym Gym::BuildCommandGenerator Standard Example #archive_path
     Failure/Error: expect(result).to match(regex)
       expected "/Users/lacostej/Library/Developer/Xcode/Archives/2015-09-22/ 2015-09-22 07.32.20.xcarchive" to match /Library\/Developer\/Xcode\/Archives\/\d\d\d\d\-\d\d\-\d\d\/ExampleProductName \d\d\d\d\-\d\d\-\d\d \d\d\.\d\d\.\d\d.xcarchive/
       Diff:
       @@ -1,2 +1,2 @@
       -/Library\/Developer\/Xcode\/Archives\/\d\d\d\d\-\d\d\-\d\d\/ExampleProductName \d\d\d\d\-\d\d\-\d\d \d\d\.\d\d\.\d\d.xcarchive/
       +"/Users/lacostej/Library/Developer/Xcode/Archives/2015-09-22/ 2015-09-22 07.32.20.xcarchive"
````

It looks like when we do the above change, we pass some options that depend on the project settings to have been read (e.g. archive_path). 

This is what is ran on the example project:

`````
 xcrun xcodebuild -showBuildSettings -scheme 'Example' -project './Example.xcodeproj' -archivePath '/Users/lacostej/Library/Developer/Xcode/Archives/2015-09-22/ 2015-09-22 07.30.16.xcarchive'
``````

Note the missing product name under ```-archivePath```

Not really sure yet if we need to call the showBuildSettings twice, once to initialize the variables that are option independent, or if we need to avoid passing all options when calling showBuildSettings.

@KrauseFx  an idea ?

**Comment by xfreebird** [comment]
This is what I was trying to do initially too, but in the end I saw that calling "showBuildSettings" twice would be inevitable.

The way I saw the solution was to have a simple "showBuildSettings" called initially to get the ```app_name``` properly initialised. And to have a different call "showBuildSettings" for the rest.

Seeing that I'm changing too many core features I decided to let you handle this, since you know better the code.

**Comment by lacostej** [comment]
I'll give it a try at implementing it with a 2 pass showBuildSettings.

**Comment by lacostej** [comment]
@xfreebird did the problem disappear ?

**Comment by xfreebird** [comment]
I thought it was fixed :)

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1854. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
